name: Deploy to Server
on:
  push:
    branches: [ main ]  # or master, depending on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Server and Move to folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/character-sheet/content/
          git pull origin main
          cp -r /root/character-sheet/content/source/content/* /root/character-sheet/content/
          rm -rf /root/character-sheet/content/source
